apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cummins-external
  namespace: kubecost
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: cummins-secretstore
    kind: SecretStore
  target:
    name: awssm-secret-access
    creationPolicy: Owner
  data:
  - secretKey: cummins-secret-key
    remoteRef:
      key: dev/apps/kubecost
      property: cummins
  #dataFrom:
  #- extract:
  #    key: data