apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-external
  namespace: kubecost
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: test-secretstore
    kind: SecretStore
  target:
    name: awssm-secret-access
    creationPolicy: Owner
  data:
  - secretKey: test
    remoteRef:
      key: dev/apps/kubecost
      property: test
  - secretKey: test-user
    remoteRef:
      key: dev/apps/kubecost/username
      property: test-user
  - secretKey: AmrCSA
    remoteRef:
      key: dev/apps/amrtest1
      property: AmrCSA
